spring.datasource.url=jdbc:mysql://mysql.railway.internal:3306/railway
spring.datasource.username=root
spring.datasource.password=bsPwWLXMbLHHPkrsFqVuMQDWAXmLuDlB
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Use Railway's PORT variable (fallback to 8080 if not set)
#server.port=${PORT:8080}